// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// subnetr_has_openmp
bool subnetr_has_openmp();
RcppExport SEXP _subnetr_subnetr_has_openmp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(subnetr_has_openmp());
    return rcpp_result_gen;
END_RCPP
}
// subnet_extract_cpp
List subnet_extract_cpp(NumericMatrix W, double r, double lambda, int obj, int min_size, int max_clusters);
RcppExport SEXP _subnetr_subnet_extract_cpp(SEXP WSEXP, SEXP rSEXP, SEXP lambdaSEXP, SEXP objSEXP, SEXP min_sizeSEXP, SEXP max_clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_clusters(max_clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(subnet_extract_cpp(W, r, lambda, obj, min_size, max_clusters));
    return rcpp_result_gen;
END_RCPP
}
// subnet_perm_cpp
List subnet_perm_cpp(NumericVector wvec, int N, double r, double lambda, int obj, int min_size, int max_clusters, int n_perm, double seed, int perm_offset, int n_threads);
RcppExport SEXP _subnetr_subnet_perm_cpp(SEXP wvecSEXP, SEXP NSEXP, SEXP rSEXP, SEXP lambdaSEXP, SEXP objSEXP, SEXP min_sizeSEXP, SEXP max_clustersSEXP, SEXP n_permSEXP, SEXP seedSEXP, SEXP perm_offsetSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_clusters(max_clustersSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type perm_offset(perm_offsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(subnet_perm_cpp(wvec, N, r, lambda, obj, min_size, max_clusters, n_perm, seed, perm_offset, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// decode_position_cpp
IntegerMatrix decode_position_cpp(NumericVector t, int N);
RcppExport SEXP _subnetr_decode_position_cpp(SEXP tSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(decode_position_cpp(t, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_subnetr_subnetr_has_openmp", (DL_FUNC) &_subnetr_subnetr_has_openmp, 0},
    {"_subnetr_subnet_extract_cpp", (DL_FUNC) &_subnetr_subnet_extract_cpp, 6},
    {"_subnetr_subnet_perm_cpp", (DL_FUNC) &_subnetr_subnet_perm_cpp, 11},
    {"_subnetr_decode_position_cpp", (DL_FUNC) &_subnetr_decode_position_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_subnetr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
