# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subnetr_has_openmp <- function() {
    .Call(`_subnetr_subnetr_has_openmp`)
}

subnet_extract_cpp <- function(W, r, lambda, obj, min_size, max_clusters) {
    .Call(`_subnetr_subnet_extract_cpp`, W, r, lambda, obj, min_size, max_clusters)
}

subnet_perm_cpp <- function(wvec, N, r, lambda, obj, min_size, max_clusters, n_perm, seed, perm_offset, n_threads) {
    .Call(`_subnetr_subnet_perm_cpp`, wvec, N, r, lambda, obj, min_size, max_clusters, n_perm, seed, perm_offset, n_threads)
}

decode_position_cpp <- function(t, N) {
    .Call(`_subnetr_decode_position_cpp`, t, N)
}

